# Generated by Django 4.1.7 on 2023-04-16 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_code', models.CharField(max_length=10, verbose_name='TS代码')),
                ('symbol', models.CharField(max_length=10, verbose_name='股票代码')),
                ('name', models.CharField(max_length=10, verbose_name='股票名称')),
                ('area', models.CharField(max_length=10, verbose_name='地域')),
                ('industry', models.CharField(max_length=10, verbose_name='所属行业')),
                ('market', models.CharField(max_length=10, verbose_name='市场类型')),
            ],
        ),
    ]
